### ISSUE TITLE
Cannot run application in Eclipse

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-comparison/GroupDocs.Comparison-for-Java-Spring#21] opened 2019-04-02 12:47 UTC
Hi, I am not able to run application on server (Tomcat 8) in Eclipse.  Server location is set to workspace metadata and server options are set to "serve modules without publishing".
I always get a "The requested resource is not available." issue. 

Can you please check this in Windows environment?

**Comment by koleslena** [comment] 2019-04-04 07:20
Hi, could you provide list of actions that give such a result?

**Comment by koleslena** [comment] 2019-04-04 12:38
Hi, try to check this https://stackoverflow.com/questions/24624782/there-are-no-resources-that-can-be-added-or-removed-from-the-server

**Comment by atirtahirgroupdocs** [comment] 2019-04-04 13:30
@koleslena I already followed this procedure. Please see this [video](https://drive.google.com/file/d/1i5enZlyxOoVKT-MVNU9OHV9r1tKk9_4a/view?usp=sharing) and let me know if there is anything wrong with the steps.
I always get a 404 error. Although application is configured.

**Comment by koleslena** [comment] 2019-04-05 08:45
please, try to use this url http://localhost:8080/comparison-spring/comparison 
for this application it is necessary to specify /comparison uri after context path

**Comment by koleslena** [comment] 2019-04-05 09:24
next step you need to do:
1 Right click at your project and select properties .
2 At the Properties windows select Maven.
3 At the right hand panel you will see Active Maven Profiles text box.
4 Please enter profile name  - war

Because we have 2 profiles in our app, and by default jar profile is active, but for deploying on external server you need war profile.

and use url http://localhost:8080/comparison-spring/comparison

Hope this steps help you!

**Comment by atirtahirgroupdocs** [comment] 2019-04-05 10:37
@koleslena I followed the steps (set war as active maven profile). But still getting same error 404.

**Comment by koleslena** [comment] 2019-04-09 09:52
Hi, I can not reproduce this problem, could you provide me with a zip archive of your eclipse project for investigation?

**Comment by koleslena** [comment] 2019-04-23 08:42
@atirtahirgroupdocs Please let me know if you could solve the problem.

**Comment by egorovpavel** [comment] 2019-06-06 07:50
@atirtahirgroupdocs We will close this issue if you still have any question feel free to reopen this issue.

**Closed by egorovpavel** 2019-06-06 07:50 UTC
Labels: help wanted
